
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package src.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 8;
  public static final int IDENT = 10;
  public static final int INTERSECCION = 6;
  public static final int OPERA = 3;
  public static final int DOS_PUNTOS = 19;
  public static final int NUM = 12;
  public static final int PAREN_IZQ = 17;
  public static final int COMA = 16;
  public static final int PAREN_DER = 18;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int UNION = 5;
  public static final int error = 1;
  public static final int ARROW = 15;
  public static final int COMPLEMENTO = 7;
  public static final int LLAVE_IZQ = 13;
  public static final int PUNTO_COMA = 20;
  public static final int ASCII = 11;
  public static final int EVALUAR = 4;
  public static final int LLAVE_DER = 14;
  public static final int RANGO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "DIFERENCIA",
  "RANGO",
  "IDENT",
  "ASCII",
  "NUM",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "ARROW",
  "COMA",
  "PAREN_IZQ",
  "PAREN_DER",
  "DOS_PUNTOS",
  "PUNTO_COMA"
  };
}

